version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - ./src/mysql/dev:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  mqtt:
    image: iegomez/mosquitto-go-auth
    ports:
      - 1883:1883
    volumes:
      - ./src/mqtt-broker:/etc/mosquitto

  auth:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 2000:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --hostname-port=2000

volumes:
  db-data: