listener 1883 0.0.0.0

auth_plugin /mosquitto/go-auth.so


auth_opt_hasher bcrypt

auth_opt_log_level debug
auth_opt_log_dest stdout


auth_opt_backends mysql
auth_opt_mysql_host cem-cloud-db-1
auth_opt_mysql_port 3306
auth_opt_mysql_user cemcloud
auth_opt_mysql_password rx9gfJWU$5aLe-tq
auth_opt_mysql_dbname cemcloud
auth_opt_mysql_userquery select mqtt_password from installation_credentials where serial_number = ? limit 1
auth_opt_mysql_superquery select count(*) from installation_credentials where serial_number = ? and is_superuser = true
auth_opt_mysql_aclquery select topic from mqtt_access_control join installation_credentials ic on ic.id = mqtt_access_control.installation_credential_id where ic.serial_number = ? and access_level = ? 
auth_opt_mysql_allow_native_passwords true