allow_anonymous true
listener 1884 0.0.0.0

auth_plugin /mosquitto/go-auth.so


auth_opt_backends jwt
auth_opt_log_level debug
auth_opt_log_dest file
auth_opt_log_file /var/log/mosquitto/mosquitto.log