server {
    server_name  cem-cloud-p5.ch;
    
    listen 443 default_server ssl http2;
    listen [::]:443 ssl http2;
    
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
        index  index.html index.htm;
    }


    location /api {
        proxy_pass http://backend:8080;
    }

}