# Set the logging levels on some packages
logging.level.root=info
logging.level.ch.fhnw.cemcloudbackend=debug

# Disable Spring Banner on startup
# spring.main.banner-mode=off

# Set the database context
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:3306/cemcloud
spring.datasource.username=${DBUSERNAME:cemcloud}
spring.datasource.password=${DBPASSWORD:rx9gfJWU$5aLe-tq}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.show-sql=true

# Set the context path under which URL the webapp is accessible
server.servlet.context-path=/api

# Set the oauth2 token issuer
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:2000/realms/cem-cloud