pluginManagement {
    repositories {
        maven { url = 'https://repo.spring.io/milestone' }
        gradlePluginPortal()
    }
    plugins {
        id 'org.springframework.boot' version "${springBootPluginVersion}"
        id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
        id 'io.github.ben-manes.versions' version "${versionsPluginVersion}"
    }
}

rootProject.name = 'cem-cloud-backend'
