name: Test and check deploy
on:
  push:
    branches:
      - '**'

env:
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Docker Compose
        run: docker-compose -f ./docker-compose-dev.yml  up -d

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run Gradle Tests
        run: ./gradlew test
        working-directory: ./src/cem-cloud-backend

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          fail_on_failure: true
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.17
    - run: npm ci
      working-directory: ./src/cem-cloud-frontend
    - run: npm run build --if-present
      working-directory: ./src/cem-cloud-frontend
    - run: npm test
      working-directory: ./src/cem-cloud-frontend
  
  build_and_deploy:
    needs: [build-and-test-backend, build-and-test-frontend]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Build Backend
      run: ./gradlew bootJar --exclude-task test
      working-directory: ./src/cem-cloud-backend

    - name: Build backend Docker image
      run: docker build -t backend-image ./src/cem-cloud-backend

    - name: Copy frontend application.json
      run: cp ./.github/workflows/application_prod.json ./src/cem-cloud-frontend/public/application.json

    - name: Build frontend Docker image
      run: docker build -t frontend-image ./src/cem-cloud-frontend

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Publish backend Docker image
      run: docker tag backend-image ghcr.io/stuni907/backend-image:latest && docker push ghcr.io/stuni907/backend-image:latest

    - name: Publish frontend Docker image
      run: docker tag frontend-image ghcr.io/stuni907/frontend-image:latest && docker push ghcr.io/stuni907/frontend-image:latest

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SERVER_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Copy docker-compose.yml to server
      run: scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./docker-compose.yml $SERVER_USERNAME@$SERVER_IP:/home/$SERVER_USERNAME
 
    - name: SSH into server and run docker-compose
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        envs: DOCKER_PASSWORD, DOCKER_USERNAME, SERVER_USERNAME        
        script: |
          docker compose -f /home/$SERVER_USERNAME/docker-compose.yml down --rmi all
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin ghcr.io
          docker compose -f /home/$SERVER_USERNAME/docker-compose.yml up -d
